[workspace]
authors = ["ahr <ahrasheed@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly/", "conda-forge"]
name = "kompass-mojo"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
mojo = "*"
cmake = "*"

[tasks]
